### PR TITLE
Add configuration for OSX

### LINKED ISSUE #2: Build for OSX
I don't know what it would take but I would be interested in having an OSX package for ray.

### PR DESCRIPTION
**Pull request by brey**
Add configuration for OSX

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Hopefully closes #2

### CODE REVIEW

**Comment by vnlitvinov** [comment]
@conda-forge-admin, please rerender

**Comment by vnlitvinov** [comment]
@brey you should have re-rendered, otherwise CI for MacOS won't get started at all... I also edited the first message to make checklist appear correctly, hope you don't mind :)

**Comment by h-vetinari** [comment]
Thanks for opening this PR. :)

**Comment by vnlitvinov** [comment]
_Now_ the fun begins... compilation errors galore 🤣

**Comment by brey** [comment]
Looks like declaration issues

**Comment by h-vetinari** [comment]
Previously this failed in lzma:
```
[1,417 / 2,647] Compiling external/com_google_googletest/googletest/src/gtest.cc; 2s darwin-sandbox ... (3 actions, 2 running)
ERROR: /Users/runner/miniforge3/conda-bld/ray-packages_1625240530036/b-o/external/org_lzma_lzma/BUILD.bazel:32:11: C++ compilation of rule '@org_lzma_lzma//:lzma' failed (Exit 1): wrapped_clang failed: error executing command 
  (cd /Users/runner/miniforge3/conda-bld/ray-packages_1625240530036/b-o/sandbox/darwin-sandbox/446/execroot/com_github_ray_project_ray && \
  [...]
```

With macos 10.14 we get further (redis), but still fail:
```
[2,576 / 2,883] Compiling external/boringssl/src/ssl/ssl_versions.cc; 1s darwin-sandbox ... (3 actions running)
INFO: From Generating C++ proto_library //streaming:streaming_proto:
protobuf/streaming.proto:5:1: warning: Import google/protobuf/any.proto is unused.
ERROR: /Users/runner/miniforge3/conda-bld/ray-packages_1626273491907/b-o/external/com_github_antirez_redis/BUILD.bazel:9:8: Executing genrule @com_github_antirez_redis//:bin failed (Exit 2): bash failed: error executing command 
  (cd /Users/runner/miniforge3/conda-bld/ray-packages_1626273491907/b-o/sandbox/darwin-sandbox/1646/execroot/com_github_ray_project_ray && \
  [...]
```

**Comment by vnlitvinov** [comment]
@krfricke as a new maintainer for this repo (and as a Ray contributor I assume) it would be awesome if you could give some help on this problem, too.

**Comment by h-vetinari** [comment]
> 
> 
> @krfricke as a new maintainer for this repo (and as a Ray contributor I assume) it would be awesome if you could give some help on this problem, too.

Absolutely. For me personally (after finishing the version upgrades), I'd much rather see #5 tackled first by someone who knows the upstream codebase/CI than OSX. 🙃

**Comment by krfricke** [comment]
I'm very happy to work on #5 - as for this PR, I'm not very familiar with the build/toolchain, but I'll look into this and can ping the right persons to help with it

**Comment by h-vetinari** [comment]
OK, a tiny step further by moving to osx 10.15 and adding `pkg-config`. Now there's a missing script:
```
make[3]: external/local_config_cc/cc_wrapper.sh: No such file or directory
```

which is interesting, because bazel itself seem to set it so (note `export CC=`):
```
ERROR: /Users/runner/miniforge3/conda-bld/ray-packages_1628785194066/b-o/external/com_github_antirez_redis/BUILD.bazel:9:8: Executing genrule @com_github_antirez_redis//:bin failed (Exit 2): bash failed: error executing command 
  (cd [...]
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; 
        export CC=external/local_config_cc/cc_wrapper.sh
        [...]
        make -s -C "${tmpdir}" -j"${parallel}" V=0 CFLAGS="${CFLAGS-} -DLUA_USE_MKSTEMP -Wno-pragmas -Wno-empty-body" AR="${AR}" RANLIB="${RANLIB}"
        [...]
    ')
```

Searching for [`cc_wrapper`](https://github.com/search?q=org%3Aconda-forge+cc_wrapper&type=code) and consequently [`gen-bazel-toolchain`](https://github.com/search?q=org%3Aconda-forge+gen-bazel-toolchain&type=code) in conda-forge, I see there's now a https://github.com/conda-forge/bazel-toolchain-feedstock, but that sounds more like cross compilation. CC @xhochy, who seems to know about these things... 🙃 

Is this a bazel-issue?

**Comment by xhochy** [comment]
Haven't looked at anything here (can do in 2 weeks).

In general bazel-toolchain is a package that generates a bazel config to use the conda-forge compilers with the correct flags in bazel. It can do cross-complilation but it is also needed normally for non-cross compiled setups.

**Comment by h-vetinari** [comment]
Thanks for the super quick response! :)

Would you say it's better to use `bazel-toolchain` rather than "stand-alone" `bazel` for conda-forge recipes (notwithstanding the pinning here...)

**Comment by hadim** [comment]
I am wondering whether there is any appetite into moving that PR forward? I don't have OSX to test the build myself locally.

**Comment by h-vetinari** [comment]
> I am wondering whether there is any appetite into moving that PR forward? I don't have OSX to test the build myself locally.

Neither do I, but you can try using CI! I haven't had time to look into the bazel-toolchain thing at the time.

**Comment by brey** [comment]
I will try locally on my Mac and see if I can get somewhere. I'll let you know.

**Comment by brey** [comment]
I will try again after rebase to `main` and do a new PR if successful.

**Comment by pyrito** [comment]
@brey has there been any progress on this front?

**Pull request closed without merging**
