### PR TITLE
Rebuild for Python 3.11

### PR DESCRIPTION
**Pull request by h-vetinari**
Bot got stuck (at least) due to the hard pin on setproctitle, see https://github.com/ray-project/ray/issues/37727

### CODE REVIEW

**Review by mattip — COMMENTED** [review]
Now it is [getting stuck](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=750416&view=logs&j=4f922444-fdfe-5dcf-b824-02f86439ef14&t=937c195f-508d-5135-dc9f-d4b5730df0f7&l=110896) on cuda:
```
Mamba failed to solve:
 - ray-tune 2.6.1.* py311h38be061_1
 - pandas
 - pyarrow >=6.0.1
 - python >=3.11,<3.12.0a0
 - python_abi 3.11.* *_cp311
 - ray-default 2.6.1.* py311h38be061_1
 - requests
 - tensorboardx >=1.9
 - python

with channels:

The reported errors are:
- Encountered problems while solving:
-   - nothing provides __cuda >=10.2 needed by pyarrow-9.0.0-py310h4a7537a_41_cuda
- 

```

**Comment by mattip** [comment]
The parallel test for python3.10 finds [`pyarrow: 12.0.1-py38h39356d1_6_cpu conda-forge`](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=750416&view=logs&j=517fe804-fa30-5dc2-1413-330699242c05&t=c7d0fcb4-3a10-5b26-dfea-e879a93fc2ab&l=110979)

I wonder why the resolver is looking for a GPU package

**Comment by h-vetinari** [comment]
Yeah, I also don't yet know where this goes off the rails. I guess we can force the cpu version here and try to get closer to the underlying failure...

**Comment by h-vetinari** [comment]
Ah, it seems that tensorboardX [forces](https://github.com/conda-forge/tensorboardx-feedstock/blob/ea6750bec1b2655282f1b82805a1b620c7665c74/recipe/meta.yaml#L30) a very new protobuf, which is incompatible with our grpcio pin on `ray-core`. I guess the other python versions are able to pull in an older tensorboardX.

We also really need to unvendor grpc & protobuf (#90), but it's just such a pain to do that with bazel 😑

**Comment by mattip** [comment]
I am not sure the grpcio problem resides entirely with bazel. See #98, where using this feedstock and `pip install grpcio==1.51.1` succeeds but `conda install <equivalent of grpcio 1.51.1>` fails.

**Comment by mattip** [comment]
I don't know whether [this PR](https://github.com/ray-project/ray/issues/35472) to remove the python grpcio dependency in favor of statically-linking to the grpc c++ library will help or hurt?

**Comment by h-vetinari** [comment]
That's sounds like it would be great in principle (we'd have to adapt it to statically link to our libgrpc, but that's not a big operation)!

**Comment by cread** [comment]
Lack of Python 3.11 support is starting to become a problem for us. Any updates on this?

**Comment by anmyachev** [comment]
> Lack of Python 3.11 support is starting to become a problem for us. Any updates on this?

The same for us.

**Comment by Garra1980** [comment]
hope https://github.com/ray-project/ray/pull/40289 will help

**Comment by mattip** [comment]
Closing, completed in #117

**Pull request closed without merging**
