### PR TITLE
unpin grpc again

### PR DESCRIPTION
**Pull request by h-vetinari**
Left-over todo, hope 1.51 works better than 1.49

### CODE REVIEW

**Comment by h-vetinari** [comment]
Still fails with a similar message as in #78 resp. https://github.com/ray-project/ray/issues/21479 (though I guess "No such file or directory" is slightly better than "Unknown Error")

```
+ python -c 'import ray; ray.init(include_dashboard=False)'
2023-01-10 06:28:18,435	ERROR services.py:1195 -- Failed to start the dashboard: Failed to start the dashboard, return code -11
 The last 10 lines of /tmp/ray/session_2023-01-10_06-28-16_600507_37276/logs/dashboard.log:
2023-01-10 06:28:18,150	WARNING head.py:248 -- `prometheus_client` not found, so metrics will not be exported.

2023-01-10 06:28:18,435	ERROR services.py:1196 -- Failed to start the dashboard, return code -11
 The last 10 lines of /tmp/ray/session_2023-01-10_06-28-16_600507_37276/logs/dashboard.log:
2023-01-10 06:28:18,150	WARNING head.py:248 -- `prometheus_client` not found, so metrics will not be exported.
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/[...]/lib/python3.8/site-packages/ray/_private/services.py", line 1181, in start_api_server
    raise Exception(err_msg + last_log_str)
Exception: Failed to start the dashboard, return code -11
 The last 10 lines of /tmp/ray/session_2023-01-10_06-28-16_600507_37276/logs/dashboard.log:
2023-01-10 06:28:18,150	WARNING head.py:248 -- `prometheus_client` not found, so metrics will not be exported.

2023-01-10 06:28:18,438	WARNING services.py:1732 -- WARNING: The object store is using /tmp instead of /dev/shm because /dev/shm has only 67104768 bytes available. This will harm performance! You may be able to free up space by deleting files in /dev/shm. If you are inside a Docker container, you can increase /dev/shm size by passing '--shm-size=1.21gb' to 'docker run' (or add it to the run_options list in a Ray cluster config). Make sure to set this to more than 30% of available RAM.
2023-01-10 06:28:19,561	INFO worker.py:1538 -- Started a local Ray instance.
[2023-01-10 06:28:20,469 E 37276 37276] core_worker.cc:179: Failed to register worker 01000000ffffffffffffffffffffffffffffffffffffffffffffffff to Raylet. IOError: [RayletClient] Unable to register worker with raylet. No such file or directory
```

Or could it have something to do with the warning, i.e. trying to access `/tmp` (which might not be present/accessible) because `/dev/shm` is too full?

**Comment by h-vetinari** [comment]
I didn't realize that ray is [building](https://github.com/ray-project/ray/blob/ray-2.2.0/bazel/ray_deps_build_all.bzl) grpc as a vendored project. This would be a pretty obviously candidate for effing something up when using a newer grpcio.

**Comment by h-vetinari** [comment]
@mattip 
I can't really ask in https://github.com/ray-project/ray/issues/21479 since you closed that (and don't feel a new issue is warranted), but WDYT about patching ray to show an output for _which_ file isn't being found by `core_worker.cc`?
```
+ python -c 'import ray; ray.init(include_dashboard=False)'
2023-09-12 06:57:17,369	WARNING services.py:1832 -- WARNING: The object store is using /tmp instead of /dev/shm because /dev/shm has only 67104768 bytes available. This will harm performance! You may be able to free up space by deleting files in /dev/shm. If you are inside a Docker container, you can increase /dev/shm size by passing '--shm-size=1.11gb' to 'docker run' (or add it to the run_options list in a Ray cluster config). Make sure to set this to more than 30% of available RAM.
2023-09-12 06:57:17,755	INFO worker.py:1621 -- Started a local Ray instance.
[2023-09-12 06:57:18,642 E 39288 39288] core_worker.cc:201: Failed to register worker 01000000ffffffffffffffffffffffffffffffffffffffffffffffff to Raylet. IOError: [RayletClient] Unable to register worker with raylet. No such file or directory
```

**Comment by mattip** [comment]
I think it is not connected to an actual disk-on-file, rather some socket-like object.

**Comment by mattip** [comment]
It may be worth waiting for the large refactor of grpcio which is meant to land in 2.7, and then to try to reproduce the problem

**Comment by mattip** [comment]
Maybe we have worked around the problem for now? There is a 3.11 build, and the pin for grpcio is now https://github.com/conda-forge/ray-packages-feedstock/blob/818fe7824d2d7240085e9f592053fc09dfbaf913/recipe/meta.yaml#L172

**Pull request closed without merging**
