### PR TITLE
Unpin nodejs (build for 14/16/18)

### PR DESCRIPTION
**Pull request by h-vetinari**
Longstanding open point since #28

### CODE REVIEW

**Comment by h-vetinari** [comment]
Is there any reason `ray-dashboard` hasn't been included in `ray-all` so far? @conda-forge/ray-packages

**Comment by h-vetinari** [comment]
> Maybe #82 is relevant?

Well, I guess that issue was closed by https://github.com/conda-forge/ray-packages-feedstock/commit/8f7fb9b1f99a2686f9326a27da6749864f9e5a80, but that commit should not have removed ray-dashboard from ray-all (let's not make our lives harder than they need to be by having to figuring out which ray-extras are transitive dependencies of each other).

**Comment by h-vetinari** [comment]
@conda-forge/ray-packages PTAL

Planning to merge this in 48h if there are no comments.

**Review by krfricke — APPROVED** [review]
LGTM

**Pull request merged**
