### PR TITLE
Updated build recipe and patches to ray-1.4.0

### PR DESCRIPTION
**Pull request by gshimansky**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by gshimansky** [comment]
@conda-forge-admin, please rerender

**Comment by gshimansky** [comment]
The build doesn't include a new ray subproject "observability" because it appears only in setup.py and nowhere else. It looks like it is some unfinished work that may appear in future releases.

**Comment by vnlitvinov** [comment]
Looks good, but let's merge #14 and #17 first.

**Comment by vnlitvinov** [comment]
> Looks good, but let's merge #14 and #17 first.

@gshimansky those PRs were merged, could you please rebase off `master` so we can continue on making Ray 1.4.0 happen on conda-forge?

**Comment by h-vetinari** [comment]
> @gshimansky those PRs were merged, could you please rebase off `master` so we can continue on making Ray 1.4.0 happen on conda-forge?

I just tried my hand at rebasing - it was trivial since this PR was already building on #14, and all but one commit were included there already.

**Comment by vnlitvinov** [comment]
> I just tried my hand at rebasing - it was trivial since this PR was already building on #14, and all but one commit were included there already.

Yeah, I thought there were more merge conflicts than I actually faced... `git` was smart enough. So I just decided to rebase myself hoping for the best 😄

**Comment by h-vetinari** [comment]
You ended up re-pushing the same thing I had pushed a few minutes before 😆 
```
C:\Users\[...]\Dev\conda-forge\ray-packages-feedstock>git status
On branch 1.4.0
Your branch and 'gshimansky/1.4.0' have diverged,
and have 1 and 1 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

nothing to commit, working tree clean

C:\Users\[...]\Dev\conda-forge\ray-packages-feedstock>git diff 1.4.0 gshimansky/1.4.0

C:\Users\[...]\Dev\conda-forge\ray-packages-feedstock>
```

**Review by h-vetinari — APPROVED** [review]

**Review by vnlitvinov — APPROVED** [review]

**Pull request merged**
