### PR TITLE
Rebuild for libabseil 20240722, libgrp 1.65 & libprotobuf 5.27.5

### PR DESCRIPTION
**Pull request by h-vetinari**
Bot got stuck on something

### CODE REVIEW

**Comment by mattip** [comment]
Something is broken. The artifact [cannot run](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1061158&view=logs&j=d818e662-7181-5ce9-b265-50d03742b7af&t=367317f3-9b77-59ac-9e12-e56370c98acd&l=81405)` 
```
ray start --head
python -c 'import ray; ray.init('\''ray://127.0.0.1:10001'\'')'
```

It fails with `ConnectionError: ray client connection timeout`

**Comment by apmorton** [comment]
https://github.com/conda-forge/ray-packages-feedstock/blob/main/recipe/patches/0005-Vendor-grpc-1.62.2.patch needs to be updated - I can take a stab today.

Also, macos builds are broken for a completely different reason:
```
In file included from external/com_google_absl/absl/base/log_severity.cc:15:
external/com_google_absl/absl/base/log_severity.h:18:10: fatal error: 'array' file not found
#include <array>
```

seems like include path isn't set correctly to find the STL.

**Comment by apmorton** [comment]
Windows builds are `fatal error C1060: compiler is out of heap space`
MacOS builds are STL include error

```
cd /Users/runner/miniforge3/conda-bld/ray-packages_1729717405472/_build_env/share/bazel/aacbef1b1d30529f93019fd9ca32a456/sandbox/darwin-sandbox/8/execroot/com_github_ray_project_ray && \
  exec env - \
    APPLE_SDK_PLATFORM=MacOSX \
    APPLE_SDK_VERSION_OVERRIDE=10.15 \
    PATH=/Users/runner/miniforge3/conda-bld/ray-packages_1729717405472/_build_env/bin:/Users/runner/miniforge3/conda-bld/ray-packages_1729717405472/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin:/Users/runner/miniforge3/condabin:/Users/runner/miniforge3/bin:/Users/runner/miniforge3/condabin:/usr/local/lib/ruby/gems/3.0.0/bin:/usr/local/opt/ruby@3.0/bin:.:/usr/local/bin:/usr/local/sbin:/Users/runner/bin:/Library/Frameworks/Python.framework/Versions/Current/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/bin:/bin:/usr/sbin:/sbin:/Users/runner/.dotnet/tools \
    XCODE_VERSION_OVERRIDE=15.2.0.15C500b \
    ZERO_AR_DATE=1 \
  external/local_config_cc/wrapped_clang_pp '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -g0 -O2 -DNDEBUG '-DNS_BLOCK_ASSERTIONS=1' '-std=c++11' 'DEBUG_PREFIX_MAP_PWD=.' -iquote external/com_google_absl -iquote bazel-out/darwin-opt-exec-2B5CBBC6/bin/external/com_google_absl -MD -MF bazel-out/darwin-opt-exec-2B5CBBC6/bin/external/com_google_absl/absl/flags/_objs/commandlineflag_internal/commandlineflag.d '-DBAZEL_CURRENT_REPOSITORY="com_google_absl"' '-frandom-seed=bazel-out/darwin-opt-exec-2B5CBBC6/bin/external/com_google_absl/absl/flags/_objs/commandlineflag_internal/commandlineflag.o' -isysroot __BAZEL_XCODE_SDKROOT__ -F__BAZEL_XCODE_SDKROOT__/System/Library/Frameworks -F__BAZEL_XCODE_DEVELOPER_DIR__/Platforms/MacOSX.platform/Developer/Library/Frameworks -no-canonical-prefixes -pthread -g0 -w -g0 '-std=c++17' -Wall -Wextra -Wc++98-compat-extra-semi -Wcast-qual -Wconversion -Wdeprecated-pragma -Wfloat-overflow-conversion -Wfloat-zero-conversion -Wfor-loop-analysis -Wformat-security -Wgnu-redeclared-enum -Winfinite-recursion -Winvalid-constexpr -Wliteral-conversion -Wmissing-declarations -Woverlength-strings -Wpointer-arith -Wself-assign -Wshadow-all -Wshorten-64-to-32 -Wsign-conversion -Wstring-conversion -Wtautological-overlap-compare -Wtautological-unsigned-zero-compare -Wundef -Wuninitialized -Wunreachable-code -Wunused-comparison -Wunused-local-typedefs -Wunused-result -Wvla -Wwrite-strings -Wno-float-conversion -Wno-implicit-float-conversion -Wno-implicit-int-float-conversion -Wno-unknown-warning-option -DNOMINMAX -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -target x86_64-apple-macosx10.15 -c external/com_google_absl/absl/flags/internal/commandlineflag.cc -o bazel-out/darwin-opt-exec-2B5CBBC6/bin/external/com_google_absl/absl/flags/_objs/commandlineflag_internal/commandlineflag.o
```

**Comment by mattip** [comment]
Thanks for moving this forward.
Poking around for why macos cannot find standard headers like `cstdint`, `cassert`, it seems `-stdlib=libc++` is needed. I would think that is added automatically for a cpp build.

**Comment by apmorton** [comment]
grand - can we get this fixed and merged and then rebase the `2.38.0` branch?

**Comment by h-vetinari** [comment]
> it seems `-stdlib=libc++` is needed. I would think that is added automatically for a cpp build.

This is indeed [part](https://github.com/conda-forge/clang-compiler-activation-feedstock/blob/99787db3e492015bc43613242093d4eb4573ad57/recipe/build.sh#L7) of our compiler activation. As long as you're not unsetting/overwriting `CXXFLAGS`, it should be there.

**Comment by h-vetinari** [comment]
Given that the failure also shows up in #184 (which should still be pulling in the old dependencies), this is probably not related to the grpc bump, but some other issue that could be unrelated to ray.

**Comment by mattip** [comment]
I will have to set up a local macos x86_64 environment to try to work this out. Maybe early next week.

**Comment by mattip** [comment]
I see `-stdlib=c++` in [the setup logs for CXXFLAGS](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1062078&view=logs&j=1dfee543-4d72-5193-7012-7358e3fc4acd&t=344bb75a-1253-525e-defa-7c6fedd7579f&l=1600) but then in the [failed compile command](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1062078&view=logs&j=1dfee543-4d72-5193-7012-7358e3fc4acd&t=344bb75a-1253-525e-defa-7c6fedd7579f&l=3831) I don't see it

**Comment by mattip** [comment]
Of course it works locally, so we will have to debug this via CI :(

**Comment by apmorton** [comment]
well, my theory was correct - its the osx 13 machine images that are the problem.

Build should be green on osx12 images and we should be good to merge.

**Comment by timkpaine** [comment]
One thing to note, I believe the `pandas<2.2` restriction on `ray-data` can be removed. Might as well through it in to the next PR that gets merged, but I'll make an issue anyway

**Comment by h-vetinari** [comment]
> well, my theory was correct - its the osx 13 machine images that are the problem.
> 
> Build should be green on osx12 images and we should be good to merge.

Could you please open an issue for that either on https://github.com/conda-forge/libcxx-feedstock or https://github.com/conda-forge/clang-compiler-activation-feedstock (depending where you think it's more appropriate)?

**Pull request merged**
