### PR TITLE
Update patches for 1.9.2

### PR DESCRIPTION
**Pull request by jjyao**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jjyao** [comment]
@conda-forge-admin, please rerender

**Comment by vnlitvinov** [comment]
Based on https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=448130&view=logs&j=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&t=841356e0-85bb-57d8-dbbc-852e683d1642&l=2100, I would assume that something went awry in the patching of Redis build, as in `conda build` environment there is no `cc` binary (and I made certain patches to set the `CC` variable with the right compiler).

**Comment by jjyao** [comment]
Seems now it's a npm issue.

**Comment by h-vetinari** [comment]
> Seems now it's a npm issue.

Based on your comment I removed the cap (i.e. to see if it passes with nodejs 17), but upon second look it seems like it's just that some file is not being found...?

```
npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /home/conda/feedstock_root/build_artifacts/ray-packages_1644080280390/work/dashboard/client/node_modules/@babel/helper-compilation-targets/node_modules/semver/bin/semver
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/home/conda/feedstock_root/build_artifacts/ray-packages_1644080280390/work/dashboard/client/node_modules/@babel/helper-compilation-targets/node_modules/semver/bin/semver'
npm ERR! enoent This is related to npm not being able to find a file.
```

And IIUC, the path to the missing file is actually in the dashboard tree, so something that ray controls.

PS. Feel free to rebase or revert out my commits.

**Comment by jjyao** [comment]
It turned out that ray only supports nodejs 14.

**Comment by jjyao** [comment]
@conda-forge-admin, please rerender

**Comment by jjyao** [comment]
@h-vetinari @vnlitvinov @krfricke I think it's ready to be merged.

**Comment by h-vetinari** [comment]
LGTM, thank you! 🙃 

(but _please_ make it a squash merge this time if you press the button, @vnlitvinov)

**Review by vnlitvinov — APPROVED** [review]
LGTM, cool!

**Pull request merged**
