### PR TITLE
Update virtualenv constraint to match public

### PR DESCRIPTION
**Pull request by claytonparnell**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Updating constraint to match https://github.com/ray-project/ray/blob/e1385a06b83d6ab5a7fcaad4d9d11911918aaf19/python/setup.py#L266 . 
Context in https://github.com/conda-forge/ray-packages-feedstock/issues/191

### CODE REVIEW

**Comment by mattip** [comment]
This will be part of the update to `ray-2.40.0`. Note previous versions will not install `virtualenv==20.21.1` since the selector excludes it (and anything above)

**Comment by claytonparnell** [comment]
@mattip can we please apply the fix to 2.39.0 as well in a new 2.39.0 build, as the PR does? This is the constraint the public repo has for 2.39.0, if it's as easy as merging the PR would appreciate releasing this asap to resolve security concerns.
https://github.com/ray-project/ray/blob/ray-2.39.0/python/setup.py#L265

**Comment by timkpaine** [comment]
this is not a fix, as explained by @mattip. I'll add that this is also not the correct way to "fix" constraints on published versions as the solver can choose older builds.

**Comment by claytonparnell** [comment]
@timkpaine thanks for the info! We had previously been using this method (updating dependency + build number) with success in our image, but the way described makes sense and we will implement it going forward. I see you've approved 2.40.0 PR will track that.

**Pull request closed without merging**
