### PR TITLE
Add the document on how to patch 3rd parties

### PR DESCRIPTION
**Pull request by vnlitvinov**
This is inspired by updating #6 - I had to remember how to work with patches, so I decided to write it down for future reference.

### CODE REVIEW

**Comment by vnlitvinov** [comment]
cc @richardliaw

**Comment by h-vetinari** [comment]
Thanks for writing this up an easy guide to patch-ception! :)

I might have asked this already in the staged-recipes PR, but could we swap out the vendored redis for the conda-forge one? I'm guessing we should also include the licenses for all the third-party vendored libraries in an easily accessible place, cf. what was done in a similar context for [rust](https://github.com/conda-forge/cryptography-feedstock/pull/64#issuecomment-780168165) by @isuruf & @ocefpaf.

**Comment by vnlitvinov** [comment]
I do not know if it's possible, let's ask Ray guys instead - @richardliaw do you know if that's possible?

As for vendored libraries - they should already be stored, for example see:

https://github.com/conda-forge/ray-packages-feedstock/blob/15971387f8012b8ccfb4dfd3c7b9a37666027f89/recipe/licenses/antirez-redis-COPYING.txt#L1-L10

**Comment by h-vetinari** [comment]
> As for vendored libraries - they should already be stored, for example see:

I'm not worried that they're not there in the ray repo, what I'm saying is that they should be represented in the feedstock as well.

**Comment by h-vetinari** [comment]
> As for vendored libraries - they should already be stored, for example see:

cool! :) I had forgotten that, sorry.

**Comment by vnlitvinov** [comment]
@h-vetinari this is ready for merging BTW

**Comment by h-vetinari** [comment]
Cool! :)

**Pull request merged**
